version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Istanbul"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "@types/babel__*"
      changesets:
        patterns:
          - "@changesets/*"
      commitlint:
        patterns:
          - "@commitlint/*"
      eslint:
        patterns:
          - "@cspell/*"
          - "@eslint/*"
          - "@types/node"
          - "eslint"
          - "eslint-*"
          - "*-eslint"
          - "globals"
      husky:
        patterns:
          - "husky"
      rimraf:
        patterns:
          - "rimraf"
      typescript:
        patterns:
          - "typescript"
